name: Arcadia

# TODO:
#   - Push the version tag on workflow_dispatch event?

on:
  push:
    branches: [master]
    # paths:
    #   - 'packages/arcadia/**'
    #   - 'services/docker/arcadia/**'
  pull_request:
    branches: [master]
    # paths:
    #   - 'packages/arcadia/**'
    #   - 'services/docker/arcadia/**'

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Compile server
        run: yarn workspace @arcadia/server build

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Build Docker Image
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pacificocean-bot --password-stdin
          docker pull ghcr.io/siberianmh/arcadia:latest || true
          docker build --pull -f "services/docker/arcadia/Dockerfile" -t ghcr.io/siberianmh/arcadia:latest --cache-from ghcr.io/siberianmh/arcadia:latest .
