name: Do Release

on:
  workflow_dispatch:
    inputs:
      version:
        description:
          'The new version for package (should be semver valid, like 0.0.0)'
        required: true
      package:
        description:
          'Package name to publish (just name, final construct is `packages/*`)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn
      - name: Run release
        run: |
          git config user.email "55543306+pacificocean-bot@users.noreply.github.com"
          git config user.name "Pacific Ocean Bot"

          echo "Building package ${{ github.event.inputs.package }}/${{ github.event.inputs.version }}"
          cd packages/${{ github.event.inputs.package }}
          yarn build

          echo "Publishing package ${{ github.event.inputs.package }}/${{ github.event.inputs.version }}"
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          yarn config set version-git-tag false
          yarn publish --new-version ${{ github.event.inputs.version }}

          git status
          git commit -m "build: release ${{ github.event.inputs.package }}/${{ github.event.inputs.version }}"
          git push
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
