name: Docker Do Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version (tag) for image'
        required: true
      image_name:
        description:
          'Image name (see docs/process/docker-release.md) for valid image names'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release Roads
        if: ${{ github.event.inputs.image_name }} == "roads"
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pacificocean-bot --password-stdin
          docker pull ghcr.io/siberianmh/roads:latest || true
          docker build --pull
            -f "services/docker/roads/Dockerfile"
            --build-arg GIT_COMMIT=${GITHUB_SHA} --build-arg VERSION=${{github.event.inputs.version}}
            -t ghcr.io/siberianmh/roads:${{github.event.inputs.version}} --cache-from ghcr.io/siberianmh/roads:latest .
          docker push ghcr.io/siberianmh/roads:${{github.event.inputs.version}}
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
