name: NPM Packages - find-me-value

on:
  push:
    branches: [master]
    paths:
      - 'packages/find-me-value/**'
  pull_request:
    branches: [master]
    paths:
      - 'packages/find-me-value/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Run tests
        run: |
          cd packages/find-me-value
          yarn test
