name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.3
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Run lint
        run: yarn lint
