name: Ozark

on:
  push:
    branches: [master]
    paths:
      - 'packages/ozark/**'
      - 'services/docker/ozark/**'
  pull_request:
    branches: [master]
    paths:
      - 'packages/ozark/**'
      - 'services/docker/ozark/**'

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Build Ozark Web
        run: |
          cd packages/ozark/web
          yarn build

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Build Docker Image
        run: |
          docker info
          docker build --pull -f "services/docker/ozark/Dockerfile" -t siberianmh/siberianmh/ozark:latest .
