name: Roads

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Build Docker Image
        run: |
          docker info
          docker build --pull -f "services/docker/roads/Dockerfile" -t siberianmh/siberianmh/roads:latest .
