name: Roads

# TODO:
#   - Push the version tag on workflow_dispatch event?

on:
  push:
    branches: [master]
    paths:
      - 'packages/roads/**'
      - 'services/docker/roads/**'
  pull_request:
    branches: [master]
    paths:
      - 'packages/roads/**'
      - 'services/docker/roads/**'

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Compile server
        run: |
          cd packages/roads/server
          yarn build

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Build Docker Image
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pacificocean-bot --password-stdin
          docker pull ghcr.io/siberianmh/roads:latest || true
          docker build --pull -f "services/docker/roads/Dockerfile" -t ghcr.io/siberianmh/roads:latest --cache-from ghcr.io/siberianmh/roads:latest .
      # We always publish unstable builds under :latest tag
      - name: Publish Latest Docker Image
        if: github['ref'] == 'refs/heads/master'
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pacificocean-bot --password-stdin
          docker push ghcr.io/siberianmh/roads:latest
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
