name: NPM Packages - roggy

on:
  push:
    branches: [master]
    # paths:
    #   - 'packages/roggy/**'
  pull_request:
    branches: [master]
    # paths:
    #   - 'packages/roggy/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Run tests
        run: |
          cd packages/roggy
          yarn test
