name: The Board

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Compile server
        run: |
          bazel build //packages/electron-discord/the-board

  docker-build:
    runs-on: ubuntu-latest

    needs:
      - compile

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Build Docker Image
        if: github['ref'] == 'refs/heads/master'
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pacificocean-bot --password-stdin
          bazel build //packages/electron-discord/the-board:docker-the-board
      - name: Publish Latest Docker Image
        if: github['ref'] == 'refs/heads/master'
        run: |
          bazel run //packages/electron-discord/the-board:push-the-board

  deploy-to-k8s:
    runs-on: ubuntu-latest

    needs:
      - docker-build

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - id: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: siberianmh-core
          location: europe-north1-a
          credentials: ${{ secrets.GCP_CREDENTIALS }}
      - name: Rollout
        run: |
          kubectl rollout restart deploy/the-board-deploy
