name: Uwulectron

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Compile Uwulectron
        run: yarn workspace @siberianmh/uwulectron build

  docker-build:
    runs-on: ubuntu-latest

    needs:
      - compile

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Build Docker Image
        if: github['ref'] == 'refs/heads/master'
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pacificocean-bot --password-stdin
          docker pull ghcr.io/siberianmh/uwulectron:latest || true
          docker build --pull -f "services/docker/uwulectron/Dockerfile" --build-arg COMMIT_SHA=${GITHUB_SHA} -t ghcr.io/siberianmh/uwulectron:latest -t ghcr.io/siberianmh/uwulectron:${GITHUB_SHA} --cache-from ghcr.io/siberianmh/uwulectron:latest .
      - name: Publish Latest Docker Image
        if: github['ref'] == 'refs/heads/master'
        run: |
          docker push ghcr.io/siberianmh/uwulectron:latest
          docker push ghcr.io/siberianmh/uwulectron:${GITHUB_SHA}

  #region Bazel
  bazel-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: siberianmh/siberianmh-but-private
          token: ${{ secrets.CR_PAT }}
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Compile server
        run: |
          bazel build //packages/electron-discord/uwulectron
  #endregion
