name: Uwulectron

on:
  push:
    branches: [master]
    paths:
      - 'packages/uwulectron-discord-bot/**'
      - 'services/uwulectron/**'
  pull_request:
    branches: [master]
    paths:
      - 'packages/uwulectron-discord-bot/**'
      - 'services/uwulectron/**'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Compile server
        run: |
          cd packages/uwulectron-discord-bot
          yarn build

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14
      - name: Build Docker Image
        run: |
          echo ${GITHUB_SHA}
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u pacificocean-bot --password-stdin
          docker pull ghcr.io/siberianmh/uwulectron:latest || true
          docker build --pull -f "services/docker/uwulectron/Dockerfile" --build-arg COMMIT=${GITHUB_SHA} -t ghcr.io/siberianmh/uwulectron:latest --cache-from ghcr.io/siberianmh/uwulectron:latest .
      - name: Publish Latest Docker Image
        if: github['ref'] == 'refs/heads/master'
        run: |
          docker push ghcr.io/siberianmh/uwulectron:latest
